services:
  - type: web
    name: bond-market-prediction
    env: static
    buildCommand: cd my-react-app && npm install && npm run build
    staticPublishPath: my-react-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
